repos: []

hooks:
  - id: pylint
    name: pylint
    entry: pylint
    args: ['workflows/airflow/dags']

  - id: pytest
    name: pytest
    entry: pytest
    args: ['workflows/airflow/dags/modules']
